let nombre_usuario = document.getElementById("nombre_usuario").value;
let tipo_documento_usuario = document.querySelector('select[name="tipo_documento_usuario"]').value;
let numero_documento_usuario = document.getElementById("numero_documento_usuario").value;  
let telefono_usuario = document.getElementById("telefono_usuario").value;
let correo_usuario = document.getElementById("correo_usuario").value;
let genero_usuario = document.querySelector('select[name="genero_usuario"]').value;
let cargo_usuario = document.querySelector('select[name="cargo_usuario"]').value;
let fecha_nacimiento_usuario = document.getElementById("fecha_nacimiento_usuario").value;
let contraseña_usuario = document.getElementById("contraseña_usuario").value;